# Generated by Django 4.0.5 on 2022-09-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0006_userprofile_followers_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(default='documents/yk_sugi_resume_new.docx', upload_to='documents/'),
        ),
    ]
