# Generated by Django 4.0.5 on 2022-09-06 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('global', '0008_alter_userprofile_resume_alter_userprofile_user_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
