# Generated by Django 4.0.5 on 2022-09-09 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('global', '0010_alter_jobs_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='request_text',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
