# Generated by Django 4.0.5 on 2022-09-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0013_alter_jobs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='user',
        ),
    ]
