# Generated by Django 4.0.5 on 2022-09-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0016_jobs_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(default=100000),
        ),
    ]
