# Generated by Django 4.0.5 on 2022-09-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0019_userprofile_video_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='request',
            field=models.TextField(default='No requests'),
        ),
    ]
